/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.paineis.adicionar;

import Controle.ProdutoControle;
import Controle.ProdutoDao;
import Modelo.Produto;
import Visao.paineis.pnlEstoque;
import Visao.principal.Menu;
import javax.swing.JOptionPane;



/**
 *
 * @author Tomas Mufume
 */
public class jEstoque extends javax.swing.JFrame {
 Produto produtos = new Produto();
 ProdutoControle controleProdutos = new ProdutoControle();
 pnlEstoque pe = new pnlEstoque();
    Menu mn = new Menu();

    /**
     * Creates new form jCliente
     */
    public jEstoque() {
        initComponents();
         pe.carregarProdutos();
         this.setLocationRelativeTo(null);
         
         
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlCliente = new javax.swing.JLabel();
        btnCancelar = new rojeru_san.RSButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPrecoAquisicao = new rojeru_san.RSMTextFull();
        txtPrecoVenda = new rojeru_san.RSMTextFull();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtProduto = new rojeru_san.RSMTextFull();
        txtQuantidade = new rojeru_san.RSMTextFull();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSalvarProduto = new rojeru_san.RSButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbTipoProduto1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Estoque");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/imagens/Add New_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Fornecedor");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 100, 20));

        jlCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlCliente.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(jlCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 396, -1, 21));

        btnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelar.setText("Cancelar");
        btnCancelar.setColorHover(new java.awt.Color(255, 51, 51));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 120, -1));

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("MZN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 40, 50));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("0.00 ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 70, 40));

        cbFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        cbFornecedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carlos", "Mateus", "Ribeiro", "Fenias", "Bombe" }));
        jPanel1.add(cbFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 210, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Produto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 42));

        txtPrecoAquisicao.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecoAquisicao.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecoAquisicao.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtPrecoAquisicao.setBotonColor(new java.awt.Color(0, 0, 0));
        txtPrecoAquisicao.setPlaceholder("");
        jPanel1.add(txtPrecoAquisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 210, -1));

        txtPrecoVenda.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecoVenda.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecoVenda.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtPrecoVenda.setBotonColor(new java.awt.Color(0, 0, 0));
        txtPrecoVenda.setPlaceholder("");
        txtPrecoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoVendaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 210, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Quantidade");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 42));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Tipo de Produto");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 42));

        txtProduto.setBackground(new java.awt.Color(204, 204, 204));
        txtProduto.setForeground(new java.awt.Color(0, 0, 0));
        txtProduto.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtProduto.setBotonColor(new java.awt.Color(0, 0, 0));
        txtProduto.setPlaceholder("");
        jPanel1.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, -1));

        txtQuantidade.setBackground(new java.awt.Color(204, 204, 204));
        txtQuantidade.setForeground(new java.awt.Color(0, 0, 0));
        txtQuantidade.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtQuantidade.setBotonColor(new java.awt.Color(0, 0, 0));
        txtQuantidade.setPlaceholder("");
        jPanel1.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 160, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 140, 30));

        btnSalvarProduto.setBackground(new java.awt.Color(102, 102, 102));
        btnSalvarProduto.setText("Adicionar");
        btnSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Preço de Aquisição");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 20));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Preço de Venda");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Total :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        cbTipoProduto1.setBackground(new java.awt.Color(204, 204, 204));
        cbTipoProduto1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbTipoProduto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sumo", "Cerveja", "Wisk", "Vinho", "Refrigerante" }));
        jPanel1.add(cbTipoProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 210, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 430, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdutoActionPerformed
        produtos.setProduto(this.txtProduto.getText());
        produtos.setQuantidade(Integer.parseInt(this.txtQuantidade.getText()));
        produtos.setTipoProduto(this.cbFornecedor.getSelectedItem().toString());
        produtos.setpCompra(Double.parseDouble(this.txtPrecoAquisicao.getText()));
        produtos.setpVenda(Double.parseDouble(this.txtPrecoVenda.getText()));
        
       if (controleProdutos.salvarProdutoController(produtos)>0){
           JOptionPane.showMessageDialog(this,"Produto salvo com sucesso! ");

           pe.carregarProdutos();
           
       }else{
           JOptionPane.showMessageDialog(this,"Erro ao salvar Produto! ");
           
       }
    }//GEN-LAST:event_btnSalvarProdutoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPrecoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoVendaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnCancelar;
    private rojeru_san.RSButton btnSalvarProduto;
    private javax.swing.JComboBox<String> cbFornecedor;
    private javax.swing.JComboBox<String> cbTipoProduto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlCliente;
    private rojeru_san.RSMTextFull txtPrecoAquisicao;
    private rojeru_san.RSMTextFull txtPrecoVenda;
    private rojeru_san.RSMTextFull txtProduto;
    private rojeru_san.RSMTextFull txtQuantidade;
    // End of variables declaration//GEN-END:variables
 
}
