/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.paineis.adicionar;

import Controle.UsuarioDao;
import javax.swing.JOptionPane;
import Visao.paineis.pnlUsuarios;

/**
 *
 * @author Tomas Mufume
 */
public class jUsuario extends javax.swing.JFrame {

    /**
     * Creates new form jCliente
     */
    public jUsuario() {
        initComponents();
       
         this.setLocationRelativeTo(null);
         
         
         
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSButton1 = new rojeru_san.RSButton();
        rSButton2 = new rojeru_san.RSButton();
        jLabel5 = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUsuario = new rojeru_san.RSMTextFull();
        txtNome = new rojeru_san.RSMTextFull();
        txtMorada = new rojeru_san.RSMTextFull();
        txtContacto = new rojeru_san.RSMTextFull();
        txtEmail = new rojeru_san.RSMTextFull();
        cbAcesso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Acidionar Novo Usuario");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/imagens/Add New_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 419, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("N. Acesso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 60, 42));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Usuário");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 57, 49));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 40, 42));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Morada");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 42));

        rSButton1.setBackground(new java.awt.Color(102, 102, 102));
        rSButton1.setText("Adicionar");
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 439, 150, -1));

        rSButton2.setBackground(new java.awt.Color(102, 102, 102));
        rSButton2.setText("Cancelar");
        rSButton2.setColorHover(new java.awt.Color(255, 0, 102));
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 439, 150, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Contacto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, 30));

        jlUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 428, 200, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 55, 29));

        txtUsuario.setBackground(new java.awt.Color(204, 204, 204));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtUsuario.setBotonColor(new java.awt.Color(0, 0, 0));
        txtUsuario.setPlaceholder("");
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 300, 40));

        txtNome.setBackground(new java.awt.Color(204, 204, 204));
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtNome.setBotonColor(new java.awt.Color(0, 0, 0));
        txtNome.setPlaceholder("");
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 300, 40));

        txtMorada.setBackground(new java.awt.Color(204, 204, 204));
        txtMorada.setForeground(new java.awt.Color(255, 255, 255));
        txtMorada.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtMorada.setBotonColor(new java.awt.Color(0, 0, 0));
        txtMorada.setPlaceholder("");
        jPanel1.add(txtMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 300, 40));

        txtContacto.setBackground(new java.awt.Color(204, 204, 204));
        txtContacto.setForeground(new java.awt.Color(255, 255, 255));
        txtContacto.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtContacto.setBotonColor(new java.awt.Color(0, 0, 0));
        txtContacto.setPlaceholder("");
        jPanel1.add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 300, 40));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtEmail.setBotonColor(new java.awt.Color(0, 0, 0));
        txtEmail.setPlaceholder("");
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 300, 40));

        cbAcesso.setBackground(new java.awt.Color(204, 204, 204));
        cbAcesso.setEditable(true);
        cbAcesso.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        cbAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));
        jPanel1.add(cbAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed
       adicionar();
    }//GEN-LAST:event_rSButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlUsuario;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSMTextFull txtContacto;
    private rojeru_san.RSMTextFull txtEmail;
    private rojeru_san.RSMTextFull txtMorada;
    private rojeru_san.RSMTextFull txtNome;
    private rojeru_san.RSMTextFull txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void adicionar() {
       int  contato = Integer.parseInt(txtContacto.getText());
    if(UsuarioDao.criarUsuario(txtUsuario.getText(),txtNome.getText(),txtMorada.getText(),contato,txtEmail.getText(),cbAcesso.getSelectedItem().toString())) {
        JOptionPane.showMessageDialog(null,"Usuario salvo com sucesso");
      //  Lista();
    }  else{
         JOptionPane.showMessageDialog(null,"Erro ao salvar usuario");
    }
    }
}
