/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.paineis;


import Controle.ClienteControle;
import Modelo.Cliente;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Tomas Mufume
 */
public class pnlClientes extends javax.swing.JPanel {
    ArrayList<Cliente> listaCliente = new ArrayList<>();
    ClienteControle controleClientes = new ClienteControle();
    Cliente clientes = new Cliente();
    String saveUpdate ;
    
    /**
     * Creates new form pnlInicio
     */
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     public pnlClientes() {
        initComponents();
        carregarClientes();
        habilitarCampos(false);
         jScrollPane1.getViewport().setBackground(Color.white );
         
    }
    
//        void LimparLista(){
//            while(tblCliente.getRowCount()!=0){
//                ((DefaultTableModel)tblCliente.getModel()).removeRow(0);
//            }
//        }
     public  void carregarClientes(){
        listaCliente = controleClientes.getListaClienteController();
        DefaultTableModel modelo = (DefaultTableModel)tblCliente.getModel();
        modelo.setNumRows(0);
        //inserir clientes na tabelaa
        int cont = listaCliente.size();
        for (int i=0; i<cont; i++){
            modelo.addRow(new Object[]{
            listaCliente.get(i).getIdCliente(),
            listaCliente.get(i).getNome(),
            listaCliente.get(i).getMorada(),
            listaCliente.get(i).getContacto(),
            listaCliente.get(i).getEmail(),
        });
        }
        
    }
      
      public void habilitarCampos(boolean go){
          txtNomeCliente.setEnabled(go);
          txtMoradaCliente.setEnabled(go);
          txtEmailCliente.setEnabled(go);
          txtContactoCliente.setEnabled(go);
          bSalvarCliente.setEnabled(go);
          }
      
      public void clean(){
          txtNomeCliente.setText("");
          txtMoradaCliente.setText("");
          txtContactoCliente.setText("");
          txtEmailCliente.setText("");
      }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new rojerusan.RSTableMetro();
        txtPesquisar = new rojeru_san.RSMTextFull();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeCliente = new rojeru_san.RSMTextFull();
        jLabel12 = new javax.swing.JLabel();
        txtEmailCliente = new rojeru_san.RSMTextFull();
        jLabel8 = new javax.swing.JLabel();
        txtMoradaCliente = new rojeru_san.RSMTextFull();
        txtContactoCliente = new rojeru_san.RSMTextFull();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nCliente = new rojeru_san.RSButton();
        btactualizar = new rojeru_san.RSButton();
        btExcluirCliente = new rojeru_san.RSButton();
        bSalvarCliente = new rojeru_san.RSButton();
        btnPesquisar = new rojeru_san.RSButton();
        bCancelar = new rojeru_san.RSButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(820, 650));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENTES");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/imagens/User Groups_100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Morada", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tblCliente.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblCliente.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tblCliente.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tblCliente.setColorSelBackgound(new java.awt.Color(102, 102, 102));
        tblCliente.setGrosorBordeFilas(0);
        tblCliente.setGrosorBordeHead(0);
        jScrollPane1.setViewportView(tblCliente);

        txtPesquisar.setBorder(null);
        txtPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        txtPesquisar.setBordeColorFocus(new java.awt.Color(102, 102, 102));
        txtPesquisar.setBotonColor(new java.awt.Color(255, 0, 51));
        txtPesquisar.setPlaceholder("Pesquisar");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jPanel4.setAlignmentX(10.0F);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Nome do Cliente");

        txtNomeCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeCliente.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtNomeCliente.setBotonColor(new java.awt.Color(0, 0, 0));
        txtNomeCliente.setPlaceholder("");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Email");

        txtEmailCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtEmailCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailCliente.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtEmailCliente.setBotonColor(new java.awt.Color(0, 0, 0));
        txtEmailCliente.setPlaceholder("");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Morada");

        txtMoradaCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtMoradaCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtMoradaCliente.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtMoradaCliente.setBotonColor(new java.awt.Color(0, 0, 0));
        txtMoradaCliente.setPlaceholder("");

        txtContactoCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtContactoCliente.setForeground(new java.awt.Color(0, 0, 0));
        txtContactoCliente.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtContactoCliente.setBotonColor(new java.awt.Color(0, 0, 0));
        txtContactoCliente.setPlaceholder("");
        txtContactoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoClienteActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Contacto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMoradaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(1, 1, 1)))
                        .addGap(10, 10, 10))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(txtMoradaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        nCliente.setBackground(new java.awt.Color(102, 102, 102));
        nCliente.setText("Novo");
        nCliente.setToolTipText("Nova Venda");
        nCliente.setColorHover(new java.awt.Color(51, 51, 51));
        nCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nClienteActionPerformed(evt);
            }
        });

        btactualizar.setBackground(new java.awt.Color(102, 102, 102));
        btactualizar.setText("Actualizar");
        btactualizar.setColorHover(new java.awt.Color(51, 51, 51));
        btactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactualizarActionPerformed(evt);
            }
        });

        btExcluirCliente.setBackground(new java.awt.Color(102, 102, 102));
        btExcluirCliente.setText("Excluir");
        btExcluirCliente.setColorHover(new java.awt.Color(51, 51, 51));
        btExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirClienteActionPerformed(evt);
            }
        });

        bSalvarCliente.setBackground(new java.awt.Color(102, 102, 102));
        bSalvarCliente.setText("Salvar");
        bSalvarCliente.setToolTipText("Salvar Produto");
        bSalvarCliente.setColorHover(new java.awt.Color(51, 51, 51));
        bSalvarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(nCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnPesquisar.setBackground(new java.awt.Color(102, 102, 102));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/imagens/Search_40px.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.setColorHover(new java.awt.Color(51, 51, 51));
        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        bCancelar.setBackground(new java.awt.Color(102, 102, 102));
        bCancelar.setText("Cancelar");
        bCancelar.setToolTipText("Nova Venda");
        bCancelar.setColorHover(new java.awt.Color(51, 51, 51));
        bCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nClienteActionPerformed
         this.habilitarCampos(true);
         saveUpdate = "salvar";
    }//GEN-LAST:event_nClienteActionPerformed

    private void btactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarActionPerformed
     saveUpdate = "alterar";
        int linha = this.tblCliente.getSelectedRow();
        try{
            int cCliente = (int)this.tblCliente.getValueAt(linha,0);
            
            //recuperar os dados da base de dados
            clientes = controleClientes.getClienteController(cCliente);
            
            //colocar na interface
            
            this.txtNomeCliente.setText(clientes.getNome());
            this.txtMoradaCliente.setText(clientes.getMorada());
           this.txtContactoCliente.setText(String.valueOf(clientes.getContacto()));
            this.txtEmailCliente.setText(clientes.getEmail());
             //this.cbFornecedor.setSelectedItem(produtos.getFornecedor()));
            this.habilitarCampos(true);
            
        }catch(Exception o){
            JOptionPane.showMessageDialog(this,"Nenhum registo selecionado! ");
        }        
    }//GEN-LAST:event_btactualizarActionPerformed

    private void txtContactoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoClienteActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        DefaultTableModel model = (DefaultTableModel)this.tblCliente.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(model);
        this.tblCliente.setRowSorter(classificador);
        String test = txtPesquisar.getText();
        classificador.setRowFilter(RowFilter.regexFilter(test, 1));
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.habilitarCampos(false);
        this.clean();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void btExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirClienteActionPerformed
        int linha =  tblCliente.getSelectedRow();
        
       int codigoProduto = (int)tblCliente.getValueAt(linha,0);
       
       if(controleClientes.excluirClienteController(codigoProduto)){
           JOptionPane.showMessageDialog(this, "Cliente Excluido com sucesso! ");
           this.carregarClientes();
           this.habilitarCampos(false);
       }else{
          JOptionPane.showMessageDialog(this, "Erro ao Excluir Cliente! ");  
       }
    }//GEN-LAST:event_btExcluirClienteActionPerformed

    private void bSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarClienteActionPerformed
     if(saveUpdate.equals("salvar")){
        this.salvarClientes();
       }else if(saveUpdate.equals("alterar")){
         this.alterarClientes();
       }   
    }//GEN-LAST:event_bSalvarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton bCancelar;
    private rojeru_san.RSButton bSalvarCliente;
    private rojeru_san.RSButton btExcluirCliente;
    private rojeru_san.RSButton btactualizar;
    private rojeru_san.RSButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSButton nCliente;
    private rojerusan.RSTableMetro tblCliente;
    private rojeru_san.RSMTextFull txtContactoCliente;
    private rojeru_san.RSMTextFull txtEmailCliente;
    private rojeru_san.RSMTextFull txtMoradaCliente;
    private rojeru_san.RSMTextFull txtNomeCliente;
    private rojeru_san.RSMTextFull txtPesquisar;
    // End of variables declaration//GEN-END:variables
private void salvarClientes(){
        clientes.setNome(this.txtNomeCliente.getText());
        clientes.setMorada(this.txtMoradaCliente.getText());
        clientes.setContacto(Integer.parseInt(this.txtContactoCliente.getText()));
        clientes.setEmail(this.txtEmailCliente.getText());        
       if (controleClientes.salvarClienteController(clientes)>0){
           JOptionPane.showMessageDialog(this,"Produto salvo com sucesso! ");

           this.carregarClientes();
           this.clean();
           this.habilitarCampos(false);
           
       }else{
           JOptionPane.showMessageDialog(this,"Erro ao salvar Produto! ");
           
       }
    
}
private void alterarClientes(){
        clientes.setNome(this.txtNomeCliente.getText());
        clientes.setMorada(this.txtMoradaCliente.getText());
        clientes.setContacto(Integer.parseInt(this.txtContactoCliente.getText()));
        clientes.setEmail(this.txtEmailCliente.getText());
        
       if (controleClientes.atualizarClienteController(clientes)){
           JOptionPane.showMessageDialog(this,"Produto alterado com sucesso! ");

           this.carregarClientes();
           this.clean();
           this.habilitarCampos(false);
           
       }else{
           JOptionPane.showMessageDialog(this,"Erro ao alterar Produto! ");
           
       }
    
}
}
