/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.paineis;

import Controle.UsuarioControle;
import Modelo.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author TM
 */
public class pnlUsuarios extends javax.swing.JPanel {
    ArrayList<Usuario> listaUsuario = new ArrayList<>();
    UsuarioControle controleUsuarios = new UsuarioControle();
    Usuario usuarios = new Usuario();
    String saveUpdate;
    

    /**
     * Creates new form PnInicio
     */
    public pnlUsuarios() {
        initComponents();
        carregarUsuarios();
        habilitarCampos(false);
         jScrollPane1.getViewport().setBackground(Color.white );
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
          public  void carregarUsuarios(){
        listaUsuario = controleUsuarios.getListaUsuarioController();
        DefaultTableModel modelo = (DefaultTableModel)tblUsuarios.getModel();
        modelo.setNumRows(0);
        //inserir usuarios na tabelaa
        int cont = listaUsuario.size();
        for (int i=0; i<cont; i++){
            modelo.addRow(new Object[]{
            listaUsuario.get(i).getIdusuario(),
            listaUsuario.get(i).getNome(),
            listaUsuario.get(i).getLogin(),
            listaUsuario.get(i).getSenha(),
            listaUsuario.get(i).getAcesso(),
        });
        }
        
    }
      
      public void habilitarCampos(boolean go){
          txtNome.setEnabled(go);
          txtUsuario.setEnabled(go);
          txtSenha.setEnabled(go);
          cbNivelAcesso.setEnabled(go);
          bSalvarUsuario.setEnabled(go);
          }
      
      public void clean(){
          txtNome.setText("");
          txtUsuario.setText("");
          txtSenha.setText("");
          cbNivelAcesso.setSelectedItem("");
      }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new rojerusan.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new rojeru_san.RSMTextFull();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUsuario = new rojeru_san.RSMTextFull();
        cbNivelAcesso = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtSenha = new rojeru_san.RSMPassView();
        jPanel5 = new javax.swing.JPanel();
        nUsuario = new rojeru_san.RSButton();
        bSalvarUsuario = new rojeru_san.RSButton();
        btactualizar = new rojeru_san.RSButton();
        btExcluirUsuario = new rojeru_san.RSButton();
        bCancelar = new rojeru_san.RSButton();
        btnPesquisar = new rojeru_san.RSButton();
        txtPesquisar = new rojeru_san.RSMTextFull();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/imagens/User Account_100px.png"))); // NOI18N
        jLabel1.setText("INÍCIO");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRO DE USUÁRIOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(820, 650));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Usuário", "Senha", "N.Acesso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tblUsuarios.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblUsuarios.setColorFilasForeground1(new java.awt.Color(102, 102, 102));
        tblUsuarios.setColorFilasForeground2(new java.awt.Color(102, 102, 102));
        tblUsuarios.setColorSelBackgound(new java.awt.Color(102, 102, 102));
        tblUsuarios.setGrosorBordeFilas(0);
        tblUsuarios.setGrosorBordeHead(0);
        jScrollPane1.setViewportView(tblUsuarios);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jPanel4.setAlignmentX(10.0F);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Nome ");

        txtNome.setBackground(new java.awt.Color(204, 204, 204));
        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        txtNome.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtNome.setBotonColor(new java.awt.Color(0, 0, 0));
        txtNome.setPlaceholder("");
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Senha");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Usuário");

        txtUsuario.setBackground(new java.awt.Color(204, 204, 204));
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtUsuario.setBotonColor(new java.awt.Color(0, 0, 0));
        txtUsuario.setPlaceholder("");
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        cbNivelAcesso.setBackground(new java.awt.Color(204, 204, 204));
        cbNivelAcesso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador" }));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Nível de Acesso");

        txtSenha.setBackground(new java.awt.Color(204, 204, 204));
        txtSenha.setForeground(new java.awt.Color(0, 0, 0));
        txtSenha.setToolTipText("");
        txtSenha.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtSenha.setBotonColor(new java.awt.Color(0, 0, 0));
        txtSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSenha.setPlaceholder("Campo de senha");
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSenhaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(cbNivelAcesso, 0, 189, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        nUsuario.setBackground(new java.awt.Color(102, 102, 102));
        nUsuario.setText("Novo");
        nUsuario.setToolTipText("Nova Venda");
        nUsuario.setColorHover(new java.awt.Color(51, 51, 51));
        nUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nUsuarioActionPerformed(evt);
            }
        });

        bSalvarUsuario.setBackground(new java.awt.Color(102, 102, 102));
        bSalvarUsuario.setText("Salvar");
        bSalvarUsuario.setToolTipText("Salvar Produto");
        bSalvarUsuario.setColorHover(new java.awt.Color(51, 51, 51));
        bSalvarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarUsuarioActionPerformed(evt);
            }
        });

        btactualizar.setBackground(new java.awt.Color(102, 102, 102));
        btactualizar.setText("Actualizar");
        btactualizar.setColorHover(new java.awt.Color(51, 51, 51));
        btactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactualizarActionPerformed(evt);
            }
        });

        btExcluirUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btExcluirUsuario.setText("Excluir");
        btExcluirUsuario.setColorHover(new java.awt.Color(51, 51, 51));
        btExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirUsuarioActionPerformed(evt);
            }
        });

        bCancelar.setBackground(new java.awt.Color(102, 102, 102));
        bCancelar.setText("Cancelar");
        bCancelar.setToolTipText("Nova Venda");
        bCancelar.setColorHover(new java.awt.Color(51, 51, 51));
        bCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(nUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPesquisar.setBackground(new java.awt.Color(102, 102, 102));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/imagens/Search_40px.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.setColorHover(new java.awt.Color(51, 51, 51));
        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        txtPesquisar.setToolTipText("Pesquisar");
        txtPesquisar.setBordeColorFocus(new java.awt.Color(102, 102, 102));
        txtPesquisar.setBotonColor(new java.awt.Color(255, 0, 51));
        txtPesquisar.setPlaceholder("Pesquisar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        DefaultTableModel model = (DefaultTableModel)this.tblUsuarios.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(model);
        this.tblUsuarios.setRowSorter(classificador);
        String test = txtPesquisar.getText();
        classificador.setRowFilter(RowFilter.regexFilter(test, 1));
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void nUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nUsuarioActionPerformed
        this.habilitarCampos(true);
        saveUpdate = "salvar";
    }//GEN-LAST:event_nUsuarioActionPerformed

    private void bSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarUsuarioActionPerformed
        if(saveUpdate.equals("salvar")){
            this.salvarUsuario();
        }else if(saveUpdate.equals("alterar")){
            this.alterarUsuario();
        }
    }//GEN-LAST:event_bSalvarUsuarioActionPerformed

    private void btactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarActionPerformed
        saveUpdate = "alterar";
        int linha = this.tblUsuarios.getSelectedRow();
        try{
            int cUsuario = (int)this.tblUsuarios.getValueAt(linha,0);

            //recuperar os dados da base de dados
            usuarios = controleUsuarios.getUsuarioController(cUsuario);

            //colocar na interface

            this.txtNome.setText(usuarios.getNome());
            this.txtUsuario.setText(usuarios.getLogin());
            this.txtSenha.setText(usuarios.getSenha());
            this.cbNivelAcesso.setSelectedItem(usuarios.getAcesso());
        this.habilitarCampos(true);

        }catch(Exception o){
            JOptionPane.showMessageDialog(this,"Nenhum registo selecionado! ");
        }
    }//GEN-LAST:event_btactualizarActionPerformed

    private void btExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirUsuarioActionPerformed
        int linha =  tblUsuarios.getSelectedRow();

        int codigoUsuario = (int)tblUsuarios.getValueAt(linha,0);

        if(controleUsuarios.excluirUsuarioController(codigoUsuario)){
            JOptionPane.showMessageDialog(this, "Usuario Excluido com sucesso! ");
            this.carregarUsuarios();
            this.habilitarCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao Excluir Usuario! ");
        }
    }//GEN-LAST:event_btExcluirUsuarioActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.habilitarCampos(false);
        this.clean();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void txtSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyTyped
         String caracter ="@!#$%^&*()-_+=][|;'º.,''´´«»></?`~\\{}:"; 
         if(caracter.contains(evt.getKeyChar()+"")){
         evt.consume();
         JOptionPane.showMessageDialog(null," nao podes usar  caracteres especiais");
   }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaKeyTyped

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
         String caracter ="@!#$%^&*()-_+=][|;'º.,''´´«»></?`~\\{}:"; 
         if(caracter.contains(evt.getKeyChar()+"")){
         evt.consume();
         JOptionPane.showMessageDialog(null," nao podes usar  caracteres especiais");
   }        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
         String caracter ="0987654321@!#$%^&*()-_+=][|;'º.,''´´«»></?`~\\{}:"; 
         if(caracter.contains(evt.getKeyChar()+"")){
         evt.consume();
         JOptionPane.showMessageDialog(null," nao podes usar numero nem caracteres especiais");
   }    
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton bCancelar;
    private rojeru_san.RSButton bSalvarUsuario;
    private rojeru_san.RSButton btExcluirUsuario;
    private rojeru_san.RSButton btactualizar;
    private rojeru_san.RSButton btnPesquisar;
    private javax.swing.JComboBox<String> cbNivelAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSButton nUsuario;
    private rojerusan.RSTableMetro tblUsuarios;
    private rojeru_san.RSMTextFull txtNome;
    private rojeru_san.RSMTextFull txtPesquisar;
    private rojeru_san.RSMPassView txtSenha;
    private rojeru_san.RSMTextFull txtUsuario;
    // End of variables declaration//GEN-END:variables
private void salvarUsuario(){
        usuarios.setNome(this.txtNome.getText());
        usuarios.setLogin(this.txtUsuario.getText());
        usuarios.setSenha(this.txtSenha.getText());
        usuarios.setAcesso(this.cbNivelAcesso.getSelectedItem().toString());
                
       if (controleUsuarios.salvarUsuarioController(usuarios)>0){
           JOptionPane.showMessageDialog(this,"Usuario salvo com sucesso! ");

           this.carregarUsuarios();
           this.clean();
           this.habilitarCampos(false);
           
       }else{
           JOptionPane.showMessageDialog(this,"Erro ao salvar Usuario! ");
           
       }
    
}
private void alterarUsuario(){
        usuarios.setNome(this.txtNome.getText());
        usuarios.setLogin(this.txtUsuario.getText());
        usuarios.setSenha(this.txtSenha.getText());
        usuarios.setAcesso(this.cbNivelAcesso.getSelectedItem().toString());
        
       if (controleUsuarios.atualizarUsuarioController(usuarios)){
           JOptionPane.showMessageDialog(this,"Usuario alterado com sucesso! ");

           this.carregarUsuarios();
           this.clean();
           this.habilitarCampos(false);
           
       }else{
           JOptionPane.showMessageDialog(this,"Erro ao alterar Usuario! ");
           
       }
    
}
}
