package Controle;
// Generated Oct 14, 2018 6:36:58 PM by Hibernate Tools 4.3.1

import Dao.DaoFornecedor;




/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private int id;
     private String nomeFornecedor;
     private String moradaFornecedor;
     private int contactoFornecedor;
     private String emailFornecedor;

    public Fornecedor() {
    }

    public Fornecedor(int id, String nomeFornecedor, String moradaFornecedor, int contactoFornecedor, String emailFornecedor) {
       this.id = id;
       this.nomeFornecedor = nomeFornecedor;
       this.moradaFornecedor = moradaFornecedor;
       this.contactoFornecedor = contactoFornecedor;
       this.emailFornecedor = emailFornecedor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNomeFornecedor() {
        return this.nomeFornecedor;
    }
    
    public void setNomeFornecedor(String nomeFornecedor) {
        this.nomeFornecedor = nomeFornecedor;
    }
    public String getMoradaFornecedor() {
        return this.moradaFornecedor;
    }
    
    public void setMoradaFornecedor(String moradaFornecedor) {
        this.moradaFornecedor = moradaFornecedor;
    }
    public int getContactoFornecedor() {
        return this.contactoFornecedor;
    }
    
    public void setContactoFornecedor(int contactoFornecedor) {
        this.contactoFornecedor = contactoFornecedor;
    }
    public String getEmailFornecedor() {
        return this.emailFornecedor;
    }
    
    public void setEmailFornecedor(String emailFornecedor) {
        this.emailFornecedor = emailFornecedor;
    }


public void armazenar() {
 
        DaoFornecedor daoFornecedor = new DaoFornecedor();
        daoFornecedor.armazenar(this);
 
    }
 
    public void alterar() {
 
        DaoFornecedor daoFornecedor = new DaoFornecedor();
        daoFornecedor.alterar(this);
    }
 
    public void excluir() {
 
        DaoFornecedor daoFornecedor = new DaoFornecedor();
        daoFornecedor.excluir(this);
    }

}


