package Modelo;
// Generated Oct 22, 2018 11:39:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idcliente;
     private String nome;
     private String morada;
     private int contacto;
     private String email;
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nome, String morada, int contacto, String email) {
        this.nome = nome;
        this.morada = morada;
        this.contacto = contacto;
        this.email = email;
    }
    public Cliente(String nome, String morada, int contacto, String email, Set vendas) {
       this.nome = nome;
       this.morada = morada;
       this.contacto = contacto;
       this.email = email;
       this.vendas = vendas;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public int getContacto() {
        return this.contacto;
    }
    
    public void setContacto(int contacto) {
        this.contacto = contacto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


