package Modelo;
// Generated Oct 22, 2018 11:39:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer idfornecedor;
     private String nome;
     private String morada;
     private int contacto;
     private String email;
     private Set produtos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(String nome, String morada, int contacto, String email) {
        this.nome = nome;
        this.morada = morada;
        this.contacto = contacto;
        this.email = email;
    }
    public Fornecedor(String nome, String morada, int contacto, String email, Set produtos) {
       this.nome = nome;
       this.morada = morada;
       this.contacto = contacto;
       this.email = email;
       this.produtos = produtos;
    }
   
    public Integer getIdfornecedor() {
        return this.idfornecedor;
    }
    
    public void setIdfornecedor(Integer idfornecedor) {
        this.idfornecedor = idfornecedor;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public int getContacto() {
        return this.contacto;
    }
    
    public void setContacto(int contacto) {
        this.contacto = contacto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


