package Modelo;
// Generated Oct 22, 2018 11:39:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer idproduto;
     private Fornecedor fornecedor;
     private Usuario usuario;
     private String produto;
     private int quantidade;
     private String tipoProduto;
     private int PCompra;
     private int PVenda;
     private Date dataValidade;
     private double TCompra;
     private double TVendas;
     private Set vendas = new HashSet(0);

    public Produto() {
    }

	
    public Produto(Fornecedor fornecedor, Usuario usuario, String produto, int quantidade, String tipoProduto, int PCompra, int PVenda, Date dataValidade, double TCompra, double TVendas) {
        this.fornecedor = fornecedor;
        this.usuario = usuario;
        this.produto = produto;
        this.quantidade = quantidade;
        this.tipoProduto = tipoProduto;
        this.PCompra = PCompra;
        this.PVenda = PVenda;
        this.dataValidade = dataValidade;
        this.TCompra = TCompra;
        this.TVendas = TVendas;
    }
    public Produto(Fornecedor fornecedor, Usuario usuario, String produto, int quantidade, String tipoProduto, int PCompra, int PVenda, Date dataValidade, double TCompra, double TVendas, Set vendas) {
       this.fornecedor = fornecedor;
       this.usuario = usuario;
       this.produto = produto;
       this.quantidade = quantidade;
       this.tipoProduto = tipoProduto;
       this.PCompra = PCompra;
       this.PVenda = PVenda;
       this.dataValidade = dataValidade;
       this.TCompra = TCompra;
       this.TVendas = TVendas;
       this.vendas = vendas;
    }
   
    public Integer getIdproduto() {
        return this.idproduto;
    }
    
    public void setIdproduto(Integer idproduto) {
        this.idproduto = idproduto;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public String getTipoProduto() {
        return this.tipoProduto;
    }
    
    public void setTipoProduto(String tipoProduto) {
        this.tipoProduto = tipoProduto;
    }
    public int getPCompra() {
        return this.PCompra;
    }
    
    public void setPCompra(int PCompra) {
        this.PCompra = PCompra;
    }
    public int getPVenda() {
        return this.PVenda;
    }
    
    public void setPVenda(int PVenda) {
        this.PVenda = PVenda;
    }
    public Date getDataValidade() {
        return this.dataValidade;
    }
    
    public void setDataValidade(Date dataValidade) {
        this.dataValidade = dataValidade;
    }
    public double getTCompra() {
        return this.TCompra;
    }
    
    public void setTCompra(double TCompra) {
        this.TCompra = TCompra;
    }
    public double getTVendas() {
        return this.TVendas;
    }
    
    public void setTVendas(double TVendas) {
        this.TVendas = TVendas;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


