package Modelo;
// Generated Oct 22, 2018 11:39:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer idvenda;
     private Cliente cliente;
     private Produto produto;
     private Usuario usuario;
     private int quantidade;
     private double PUnitario;
     private double PTotal;
     private Date dataVenda;

    public Venda() {
    }

    public Venda(Cliente cliente, Produto produto, Usuario usuario, int quantidade, double PUnitario, double PTotal, Date dataVenda) {
       this.cliente = cliente;
       this.produto = produto;
       this.usuario = usuario;
       this.quantidade = quantidade;
       this.PUnitario = PUnitario;
       this.PTotal = PTotal;
       this.dataVenda = dataVenda;
    }
   
    public Integer getIdvenda() {
        return this.idvenda;
    }
    
    public void setIdvenda(Integer idvenda) {
        this.idvenda = idvenda;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public double getPUnitario() {
        return this.PUnitario;
    }
    
    public void setPUnitario(double PUnitario) {
        this.PUnitario = PUnitario;
    }
    public double getPTotal() {
        return this.PTotal;
    }
    
    public void setPTotal(double PTotal) {
        this.PTotal = PTotal;
    }
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }




}


